# Sample of the simplest configuration you can write

services:
  - name: service01
    strategy: "RoundRobin"
    matcher: "/"
    replicas:
      - url: "http://localhost:8081"
      - url: "http://localhost:8082"